@template.layout.page(
    content = @`
        <div class="px-4 py-5 my-5 text-center">
            <h1 class="display-5 fw-bold text-body-emphasis">Hello, world!</h1>
            <div class="col-lg-6 mx-auto">
                <p class="lead mb-4">
                    This project is made with Javalin and Bootstrap by Elisa Moritz
                </p>
            </div>
        </div>
    `
)
